name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:  # Corrected typo in job name
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Hola Body2120!"